### ISSUE TITLE
logviewer update

### ISSUE THREAD

**Issue by MonkeyNo28** [i96751414/script.logviewer#10]
the new update i96751414-2.1.3+gotham.1 fails on kodi 17.6 / installs fine on 18.2

**Comment by i96751414** [comment]
Can you please post a log file for this? Note that the last update only addressed some translation issues.

**Comment by MonkeyNo28** [comment]
there was a MD5 mismatch after download expected XXXXX was (blank)

![log](https://user-images.githubusercontent.com/51243676/81841630-be23ea80-9518-11ea-972d-d4f928a1d943.png)

**Comment by i96751414** [comment]
This seems not related with logviewer, as Kodi is the responsible for doing these updates. Maybe a network problem caused this?
Please have a look at https://forum.kodi.tv/showthread.php?tid=331692
