### ISSUE TITLE
Not working on Omega Alpha 3

### ISSUE THREAD

**Issue by TheKidRock** [i96751414/script.logviewer#14]
I installed "Log Viewer for Kodi" from Kodi repo on Android TV. However, whenever I get error notification, it does not display the error on the screen (though I have enabled to show error on screen). And the error logs (new and old) are also empty.

Is this addon not compatible with Omega?

**Comment by i96751414** [comment]
This addon has not been tested with Omega yet. However it will (eventually) support Omega

**Comment by i96751414** [comment]
I've just tested with Beta 3 and everything seems to be ok. Can you confirm the error still exists?
