### ISSUE TITLE
Estuary specific includes throw warnings with other skins

### ISSUE THREAD

**Issue by nonJon** [i96751414/script.logviewer#15]
Window .xml files contain this include: Animation_DialogPopupOpenClose

This generates warnings in the kodi log when this add-on is used with any other skin.  Not to mention the animation effect is lost.  Wouldn't it make sense to import the contents of that include directly into the window .xml files to make the log viewer more skin agnostic?

**Comment by i96751414** [comment]
Agreed. Will fix it soon

**Comment by nonJon** [comment]
Thanks! Would say the same about the DepthOSD constant.  Although less consequential, it still only works for estuary users.

**Comment by i96751414** [comment]
I just did some changes, hopefully that's it. Can you please test it?

**Comment by nonJon** [comment]
Good to go.  No more warnings and the window is animating properly now.  thx
