### ISSUE TITLE
Implement error message filters

### ISSUE THREAD

**Issue by kekukui** [i96751414/script.logviewer#2]
Regarding the option **"Show log when error occurs":** this is a great feature but it needs some filtering  since non-critical errors are constantly being logged.

**METHOD 1**

**Toggles:** dont toast error message if the message contains one of the selected strings:

CCurlFile::
CVideoPlayer::
Direct texture file loading failed
Previous line repeats
asked to focus
URL IS
Error getting
Resolver error
open failed with code
failed to open source
error opening
failed read
_________
**METHOD 2**

**Toggle:** show only exceptions
(obviously easier to implement and sufficient for many troubleshooting purposes)

**Comment by i96751414** [comment]
Thanks, will update soon.

**Comment by Grossdm** [comment]
Just a friendly reminder about this issue, in case @i96751414 still plans to update.

@h3298, if you are able to write some code for your suggestions, I'm sure @i96751414 would appreciate a pull request.

Thanks for everyone's efforts,
Doug®

**Comment by kekukui** [comment]
sorry guys, am busy with another project and unable to contribute at the moment

**Comment by i96751414** [comment]
Hi guys, I believe this is now fixed. Please try it and give your feedback before pushing this to the official repo. Cheers

**Comment by kekukui** [comment]
**Seems like a few bugs here...**

1. SLOW DISPLAY
When trying "Show Log" , 100% CPU & long delay before log appears
(see log viewer menu from Indigo add-on for comparison -- my 1000 page log appears instantly)

2. MENU CORRUPTION
After scrolling through entire log and returning to top, menu options randomly disappear or duplicate, like this:

  Show Log
  Show Log
  Show old Log
  Show old Log
  Settings
  Settings

3. CONTROLS ARE REVERSED
**Show (current) log** shows **OLD** log, etc.
___________________________________________________________________
May I suggest you just use the log display from Indigo
https://github.com/tvaddonsco/plugin.program.indigo/blob/master/textviewer.py

**Comment by i96751414** [comment]
Hi. This seems really strange. Those things can't really happen, specially the menu corruption as those options are not dynamic...

**Comment by kekukui** [comment]
hmmm, maybe its memory corruption and the cause is elsewhere.  All I know at the moment is, the Indigo log still works smoothly.  Will try another Kodi box or desktop install when I have time.

**Comment by kekukui** [comment]
**Sorry for the delay -- testing on Leia RC now and it seems to be working fine.**

![screenshot005](https://user-images.githubusercontent.com/20834957/51142280-7b191080-1819-11e9-9b99-9685145da3dc.png)

**Comment by kekukui** [comment]
Did you increment the version number and submit to Kodi repo ?
